### ISSUE TITLE
Decode capabilities

### ISSUE THREAD

**Issue by chris-ware** [bepsvpt/blurhash#2]
It'd be great to be able to take a given blurhash and decode it into a usable image

**Comment by bepsvpt** [comment]
Could you give

Could you provide some scenarios which will use decode method?

**Comment by chris-ware** [comment]
Rendering of a pre-existing blurhash into a usable image... via PHP, as in some scenarios, JS based solutions don't make sense, such as using a blurhash before loading the original image. JS would have to process the blurhash and render it whilst the browser is still downloading the image. This approach means that returned responses would include the decoded blurhash as a data-url for the image that could be either swapped or used as a background image.

**Comment by Stancobridge** [comment]
> Rendering of a pre-existing blurhash into a usable image... via PHP, as in some scenarios, JS based solutions don't make sense, such as using a blurhash before loading the original image. JS would have to process the blurhash and render it whilst the browser is still downloading the image. This approach means that returned responses would include the decoded blurhash as a data-url for the image that could be either swapped or used as a background image.

It will make sense for this to be implemented, because in some cases some developers are not familiar with the JS implementation and will find it difficult to, and secondly processing and decoding a hash u didn't encode might not give expected results as the JS developer might not know the parameters used when hashing the image

**Comment by mattvb91** [comment]
Currently looking for exactly this too. 

I dont want to decode & rerender on the frontend due to me needing more libraries on both my frontend & in my node docker container so I would love to be able to just decode the hash directly on my api endpoint so I can serve & cache it as required from there.

**Comment by bepsvpt** [comment]
Hi @chris-ware, @Stancobridge, @mattvb91 

Version 2 supports the decode function now, and you can upgrade to try it.
